name: EKS Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 3. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 4. Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Plan Terraform
    - name: Terraform Plan
      run: terraform plan

    # 6. Apply Terraform
    - name: Terraform Apply
      if: success()  # Solo si el plan fue exitoso
      run: terraform apply -auto-approve

